server {
    listen 80;
    root /usr/share/nginx/viewer;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /output {
        alias /usr/share/nginx/output/;
        default_type text/csv;
    }
}
